#!/bin/sh
wmake $WM_PROJECT_USER_DIR/src/lagrangian/spray
wmake $WM_PROJECT_USER_DIR/src/thermophysicalModels/thermoPhysicalProperties

wmake $WM_PROJECT_USER_DIR/applications/solvers/lagrangian/secondaryBreakupFoam
